version: "3.9"
services:
  catalog:
    build: ./services/catalog
    container_name: catalog
    ports:
      - "5001:5000"
    networks:
      - ms-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/items"]
      interval: 10s
      retries: 5

  users:
    build: ./services/users
    container_name: users
    ports:
      - "5002:5000"
    networks:
      - ms-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/users/1"]
      interval: 10s
      retries: 5

  orders:
    build: ./services/orders
    container_name: orders
    ports:
      - "5003:5000"
    networks:
      - ms-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/orders"]
      interval: 10s
      retries: 5

  gateway:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    networks:
      - ms-net
    depends_on:
      - catalog
      - users
      - orders

networks:
  ms-net:
